# MA429 Summative Project (Section 1-2)

- **Input Datasets**: Divvy Bike Sharing Data (Jan 2024 - Mar 2025)
- **Final Output**: Concatenated and cleaned Dataset "divvy_cleaned.parquet"
- **Section 1-2**: Datasets Loading and Data Cleaning

---
## 1. Load Original Datasets

### 1.1 Import libraries

In [13]:
import pandas as pd
import numpy as np
import os
import glob

### 1.2 Load all CSV files from the dataset folder and concatenate all monthly files into one DataFrame

In [14]:
# Path to the folder containing monthly Divvy trip CSV files
data_folder = "Divvy Bike Sharing Data Jan 2024 - Mar 2025"
pattern = os.path.join(data_folder, "*.csv")
csv_files = sorted(glob.glob(pattern))

# Load each CSV and combine into one DataFrame
dfs = []
for path in csv_files:
    df_chunk = pd.read_csv(path, low_memory=False)
    dfs.append(df_chunk)

df = pd.concat(dfs, ignore_index=True)
print(f"Combined shape: {df.shape[0]:,} rows, {df.shape[1]} columns.")
df.head()

Combined shape: 6,449,292 rows, 13 columns.

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C1D650626C8C899A,electric_bike,2024-01-12 15:30:27,2024-01-12 15:37:59,Wells St & Elm St,KA1504000135,Kingsbury St & Kinzie St,KA1503000043,41.903267,-87.634737,41.889177,-87.638506,member
1,EECD38BDB25BFCB0,electric_bike,2024-01-08 15:45:46,2024-01-08 15:52:59,Wells St & Elm St,KA1504000135,Kingsbury St & Kinzie St,KA1503000043,41.902937,-87.634440,41.889177,-87.638506,member
2,F4A9CE78061F17F7,electric_bike,2024-01-27 12:27:19,2024-01-27 12:35:19,Wells St & Elm St,KA1504000135,Kingsbury St & Kinzie St,KA1503000043,41.902951,-87.634470,41.889177,-87.638506,member
3,0A0D9E15EE50B171,classic_bike,2024-01-29 16:26:17,2024-01-29 16:56:06,Wells St & Randolph St,TA1305000030,Larrabee St & Webster Ave,13193,41.884295,-87.633963,41.921822,-87.644140,member
4,33FFC9805E3EFF9A,classic_bike,2024-01-31 05:43:23,2024-01-31 06:09:35,Lincoln Ave & Waveland Ave,13253,Kingsbury St & Kinzie St,KA1503000043,41.948797,-87.675278,41.889177,-87.638506,member

### 1.3 Initial data overview

In [15]:
# Shape and column info
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nData types:")
print(df.dtypes)
print("\nFirst few rows:")
df.head(10)

Shape: (6449292, 13)

Columns: ['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual']

Data types:
ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

First few rows:

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C1D650626C8C899A,electric_bike,2024-01-12 15:30:27,2024-01-12 15:37:59,Wells St & Elm St,KA1504000135,Kingsbury St & Kinzie St,KA1503000043,41.903267,-87.634737,41.889177,-87.638506,member
1,EECD38BDB25BFCB0,electric_bike,2024-01-08 15:45:46,2024-01-08 15:52:59,Wells St & Elm St,KA1504000135,Kingsbury St & Kinzie St,KA1503000043,41.902937,-87.634440,41.889177,-87.638506,member
2,F4A9CE78061F17F7,electric_bike,2024-01-27 12:27:19,2024-01-27 12:35:19,Wells St & Elm St,KA1504000135,Kingsbury St & Kinzie St,KA1503000043,41.902951,-87.634470,41.889177,-87.638506,member
3,0A0D9E15EE50B171,classic_bike,2024-01-29 16:26:17,2024-01-29 16:56:06,Wells St & Randolph St,TA1305000030,Larrabee St & Webster Ave,13193,41.884295,-87.633963,41.921822,-87.644140,member
4,33FFC9805E3EFF9A,classic_bike,2024-01-31 05:43:23,2024-01-31 06:09:35,Lincoln Ave & Waveland Ave,13253,Kingsbury St & Kinzie St,KA1503000043,41.948797,-87.675278,41.889177,-87.638506,member
5,C96080812CD285C5,classic_bike,2024-01-07 11:21:24,2024-01-07 11:30:03,Wells St & Elm St,KA1504000135,Kingsbury St & Kinzie St,KA1503000043,41.903222,-87.634324,41.889177,-87.638506,member
6,0EA7CB313D4F456A,classic_bike,2024-01-05 14:44:12,2024-01-05 14:53:06,Wells St & Elm St,KA1504000135,Kingsbury St & Kinzie St,KA1503000043,41.903222,-87.634324,41.889177,-87.638506,member
7,EE11F3A3B39CFBD8,electric_bike,2024-01-04 18:19:53,2024-01-04 18:28:04,Wells St & Elm St,KA1504000135,Kingsbury St & Kinzie St,KA1503000043,41.903368,-87.634861,41.889177,-87.638506,member
8,63E83DE8E3279F15,classic_bike,2024-01-01 14:46:53,2024-01-01 14:57:02,Wells St & Elm St,KA1504000135,Kingsbury St & Kinzie St,KA1503000043,41.903222,-87.634324,41.889177,-87.638506,member
9,8005682869122D93,electric_bike,2024-01-03 19:31:08,2024-01-03 19:40:05,Clark St & Ida B Wells Dr,TA1305000009,Kingsbury St & Kinzie St,KA1503000043,41.876033,-87.630866,41.889177,-87.638506,member

---
## 2. Data Cleaning

This section handles:
- **Missing values**: identify and impute or drop as appropriate
- **Duplicate records**: detect and remove exact duplicates
- **Outliers**: identify and handle unreasonable values (e.g. trip duration, coordinates)
- **Feature processing**: convert dtypes, parse dates, and standardise key columns

### 2.1 Missing value analysis

Count missing values per column and compute the percentage of missing data to decide handling strategy.

In [16]:
# Count missing values per column
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({"count": missing, "percent": missing_pct}).sort_values("count", ascending=False)
missing_df = missing_df[missing_df["count"] > 0]
print("Columns with missing values:")
if len(missing_df) > 0:
    pd.set_option("display.max_rows", None)
    print(missing_df.to_string())
    pd.reset_option("display.max_rows")
else:
    print("None")
print("\nTotal missing count:", df.isnull().sum().sum())

Columns with missing values:
                      count  percent
end_station_name    1213959    18.82
end_station_id      1213959    18.82
start_station_name  1178068    18.27
start_station_id    1178068    18.27
end_lat                7591     0.12
end_lng                7591     0.12

Total missing count: 4799236

### 2.2 Missing value handling

#### 2.2.1 Drop rows with missing values in critical columns
Critical columns: trip start/end times (`started_at`, `ended_at`), ride identifier (`ride_id`), and coordinates (`start_lat`, `start_lng`, `end_lat`, `end_lng`). Optional columns such as station names are handled in the next step.

In [17]:
# Critical columns: timestamps, ride ID, and coordinates
time_cols = [c for c in df.columns if c in ('started_at', 'ended_at')]
id_col = [c for c in df.columns if "ride_id" in c.lower() or c.lower() == "id"]
coord_cols = [c for c in df.columns if "lat" in c.lower() or "lng" in c.lower() or "lon" in c.lower()]
critical_cols = list(set(time_cols + id_col + coord_cols))
critical_cols = [c for c in critical_cols if c in df.columns]

# Treat empty strings as missing (read_csv leaves '' as-is; dropna only drops NaN)
for c in critical_cols:
    if df[c].dtype == object:
        df[c] = df[c].replace("", np.nan)

# Drop rows where any critical column is missing
before = len(df)
df = df.dropna(subset=critical_cols, how="any")
print(f"Dropped {before - len(df)} rows with missing critical columns.")

Dropped 7591 rows with missing critical columns.

### 2.2.2 Fill remaining missing values in non-critical columns

For categorical or identifier columns (e.g. station name, station ID), we can fill missing values with a placeholder like "Unknown" so that rows are retained for duration/location analysis.

In [18]:
# Fill missing values in object/string columns with "Unknown" (e.g. station names)
obj_cols = df.select_dtypes(include=["object"]).columns
for col in obj_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna("Unknown")
        print(f"Filled missing in '{col}' with 'Unknown'.")

# For numeric columns we could impute (e.g. median) or leave as NaN and drop later; here we report
num_missing = df.select_dtypes(include=[np.number]).columns[df.select_dtypes(include=[np.number]).isnull().any()]
if len(num_missing) > 0:
    print("\nNumeric columns still with missing:", num_missing.tolist())
print("\nMissing count after handling:", df.isnull().sum().sum())

Filled missing in 'start_station_name' with 'Unknown'.
Filled missing in 'start_station_id' with 'Unknown'.
Filled missing in 'end_station_name' with 'Unknown'.
Filled missing in 'end_station_id' with 'Unknown'.

Missing count after handling: 0

### 2.3 Duplicate records

Detect and remove exactly duplicate rows. Since ride ID should be unique, we also remove duplicates based on that column so each ride appears once.

In [19]:
# Count full row duplicates
n_dup_rows = df.duplicated().sum()
print("Number of fully duplicate rows:", n_dup_rows)
df = df.drop_duplicates(ignore_index=True)
print("Rows after removing full duplicates:", len(df))

# If there is a column with same ride ID, remove duplicates by that key
ride_id_col = [c for c in df.columns if "ride_id" in c.lower() or c.lower() == "id"]
if ride_id_col:
    ride_id_col = ride_id_col[0]
    before = len(df)
    df = df.drop_duplicates(subset=[ride_id_col], keep="first", ignore_index=True)
    print(f"Removed {before - len(df)} rows with duplicate '{ride_id_col}'.")
print("Final row count after duplicate removal:", len(df))

Number of fully duplicate rows: 15
Rows after removing full duplicates: 6441686
Removed 211 rows with duplicate 'ride_id'.
Final row count after duplicate removal: 6441475

### 2.4 Outlier detection and handling

We identify and handle outliers in two steps: trip duration (2.5.1) and coordinates (2.5.2).

#### 2.4.1 Trip duration outliers

Derive duration from start/end timestamps and remove: (1) invalid or negative duration (e.g. end time before start time); (2) trips shorter than 60 seconds (often false starts); (3) trips longer than 24 hours (unrealistic).

In [20]:
start_time_col = "started_at" if "started_at" in df.columns else None
end_time_col = "ended_at" if "ended_at" in df.columns else None

if start_time_col and end_time_col:
    raw_start = df[start_time_col].copy()
    raw_end = df[end_time_col].copy()
    fmt_slash = "%Y/%m/%d %H:%M:%S"
    for col, raw in [(start_time_col, raw_start), (end_time_col, raw_end)]:
        parsed = pd.to_datetime(raw, format=fmt_slash, errors="coerce")
        still_na = parsed.isna() & raw.notna()
        if still_na.any():
            fallback = pd.to_datetime(raw.loc[still_na], format="%Y-%m-%d %H:%M:%S", errors="coerce")
            parsed = parsed.fillna(fallback)
        still_na = parsed.isna() & raw.notna()
        if still_na.any():
            parsed = parsed.fillna(pd.to_datetime(raw.loc[still_na], errors="coerce"))
        df[col] = parsed
    df["duration_seconds"] = (df[end_time_col] - df[start_time_col]).dt.total_seconds()
    invalid_time = (df["duration_seconds"].isna()) | (df["duration_seconds"] < 0)
    print("Rows with invalid or negative duration:", invalid_time.sum())
    df = df.loc[~invalid_time].copy()
    # Remove too-short trips (e.g. < 60 seconds) and too-long (e.g. > 24 hours)
    too_short = df["duration_seconds"] < 60
    too_long = df["duration_seconds"] > 24 * 3600
    print("Trips shorter than 60 seconds:", too_short.sum())
    print("Trips longer than 24 hours:", too_long.sum())
    df = df.loc[~too_short & ~too_long].copy()
    print("Rows after duration-based outlier removal:", len(df))
else:
    print("Start/end time columns not found; skipping duration-based outlier removal.")

Rows with invalid or negative duration: 227
Trips shorter than 60 seconds: 143395
Trips longer than 24 hours: 401
Rows after duration-based outlier removal: 6297452

#### 2.4.2 Coordinate outliers

Remove rows where start/end coordinates are outside the valid Chicago/Divvy service area bounds. The bounds are derived from the City of Chicago ArcGIS **Chicago Boundary** extent (DensityDivvy layer, EPSG:3857), converted to WGS84 latitude/longitude in the code below. This filters out bad GPS or test data.

**Bounds source:** [Chicago Boundary, DensityDivvy (FeatureServer 4)](https://services.arcgis.com/GL0fWlNkwysZaKeV/ArcGIS/rest/services/DensityDivvy_WFL1/FeatureServer/4) — extent XMin/XMax/YMin/YMax in Spatial Reference 102100 (3857), converted to lat/lon.

In [21]:
# Chicago/Divvy service area bounds from City of Chicago ArcGIS (DensityDivvy, Chicago Boundary, EPSG:3857)
import math
x_min, x_max = -9789690.25049395, -9742702.96309587
y_min, y_max = 5107797.66836688, 5164612.45442273
R = 20037508.34  # half-equatorial circumference (m) for Web Mercator
LON_MIN = x_min * 180 / R
LON_MAX = x_max * 180 / R
LAT_MIN = math.degrees(2 * math.atan(math.exp(y_min * math.pi / R)) - math.pi / 2)
LAT_MAX = math.degrees(2 * math.atan(math.exp(y_max * math.pi / R)) - math.pi / 2)

lat_cols = [c for c in df.columns if "lat" in c.lower()]
lon_cols = [c for c in df.columns if "lng" in c.lower() or "lon" in c.lower()]
if lat_cols or lon_cols:
    before = len(df)
    for col in lat_cols:
        df = df.loc[df[col].between(LAT_MIN, LAT_MAX)]
    for col in lon_cols:
        df = df.loc[df[col].between(LON_MIN, LON_MAX)]
    print(f"Removed {before - len(df)} rows with out-of-range coordinates.")
else:
    print("No latitude/longitude columns found; skipping coordinate filtering.")
print("Rows after coordinate cleaning:", len(df))

Removed 60482 rows with out-of-range coordinates.
Rows after coordinate cleaning: 6236970

### 2.5 Initial feature processing

Convert columns to appropriate types and add derived features useful for analysis:
- Ensure datetime columns are of type `datetime64`
- Convert categorical columns (e.g. rideable type, member/casual) to `category` to save memory
- Add derived columns: `duration_seconds`, `duration_minutes`, `day_of_week`, `month`, `year`

In [22]:
# Ensure datetime columns are parsed (only started_at/ended_at; avoid matching 'station')
fmt_dt = "%Y/%m/%d %H:%M:%S"
for col in ["started_at", "ended_at"]:
    if col not in df.columns:
        continue
    if df[col].dtype == object:
        parsed = pd.to_datetime(df[col], format=fmt_dt, errors="coerce")
        still_na = parsed.isna() & df[col].notna()
        if still_na.any():
            parsed = parsed.fillna(pd.to_datetime(df.loc[still_na, col], format="%Y-%m-%d %H:%M:%S", errors="coerce"))
        df[col] = parsed

# Convert likely categorical columns to category dtype (saves memory)
candidate_cats = [c for c in df.columns if df[c].dtype == "object" and df[c].nunique() < 50]
for col in candidate_cats:
    df[col] = df[col].astype("category")

# Add duration in minutes if we have duration_seconds
if "duration_seconds" in df.columns:
    df["duration_minutes"] = (df["duration_seconds"] / 60).round(2)

# Add date-related features from start time column if available
start_col = "started_at" if "started_at" in df.columns else None
if start_col and pd.api.types.is_datetime64_any_dtype(df[start_col]):
    df["day_of_week"] = df[start_col].dt.day_name()
    df["month"] = df[start_col].dt.month
    df["year"] = df[start_col].dt.year
    print("Added derived columns: day_of_week, month, year.")
print("Feature processing complete.")
df.dtypes

Added derived columns: day_of_week, month, year.
Feature processing complete.

ride_id                       object
rideable_type               category
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual               category
duration_seconds             float64
duration_minutes             float64
day_of_week                   object
month                          int32
year                           int32
dtype: object

### 2.6 Cleaned dataset summary

In [23]:
# Summary of cleaned data
print("Cleaned dataset shape:", df.shape)
print("\nColumn dtypes:")
print(df.dtypes)
print("\nSample of cleaned data:")
df.head()

Cleaned dataset shape: (6236970, 18)

Column dtypes:
ride_id                       object
rideable_type               category
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual               category
duration_seconds             float64
duration_minutes             float64
day_of_week                   object
month                          int32
year                           int32
dtype: object

Sample of cleaned data:

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,duration_seconds,duration_minutes,day_of_week,month,year
0,C1D650626C8C899A,electric_bike,2024-01-12 15:30:27,2024-01-12 15:37:59,Wells St & Elm St,KA1504000135,Kingsbury St & Kinzie St,KA1503000043,41.903267,-87.634737,41.889177,-87.638506,member,452.0,7.53,Friday,1,2024
1,EECD38BDB25BFCB0,electric_bike,2024-01-08 15:45:46,2024-01-08 15:52:59,Wells St & Elm St,KA1504000135,Kingsbury St & Kinzie St,KA1503000043,41.902937,-87.634440,41.889177,-87.638506,member,433.0,7.22,Monday,1,2024
2,F4A9CE78061F17F7,electric_bike,2024-01-27 12:27:19,2024-01-27 12:35:19,Wells St & Elm St,KA1504000135,Kingsbury St & Kinzie St,KA1503000043,41.902951,-87.634470,41.889177,-87.638506,member,480.0,8.00,Saturday,1,2024
3,0A0D9E15EE50B171,classic_bike,2024-01-29 16:26:17,2024-01-29 16:56:06,Wells St & Randolph St,TA1305000030,Larrabee St & Webster Ave,13193,41.884295,-87.633963,41.921822,-87.644140,member,1789.0,29.82,Monday,1,2024
4,33FFC9805E3EFF9A,classic_bike,2024-01-31 05:43:23,2024-01-31 06:09:35,Lincoln Ave & Waveland Ave,13253,Kingsbury St & Kinzie St,KA1503000043,41.948797,-87.675278,41.889177,-87.638506,member,1572.0,26.20,Wednesday,1,2024

### 2.7 Save cleaned data

Save the cleaned DataFrame to a parquet file for use in later notebooks. 

**Note**: The file is large (around 6 million rows), so we saved it to parquet instead of CSV.

In [24]:
# Save cleaned dataset to parquet (use this path when loading in later notebooks)
OUTPUT_PATH = "divvy_cleaned.parquet"
df.to_parquet(OUTPUT_PATH, index=False)
print("Cleaned data saved to", OUTPUT_PATH)

Cleaned data saved to divvy_cleaned.parquet